spring.application.name=LMS
<<<<<<< HEAD

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/lms
spring.datasource.username=root
spring.datasource.password=2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
=======
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/LMS?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=69911092@CR

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
>>>>>>> 76e122be1c37dda4cb75c26f910c231dd140d776
